# ------------------------------
# グループを作成する
# ------------------------------

---
- hosts: all
  sudo: true
  user: ansible

  var_files:
    ./vars/groups.yml

  tasks:
    - group:
       name: {{ item.name }}
       gid: {{ item.gid }}
#       state: absent      #削除時にコメントアウト解除する 
    with_items: 
      - {{ groups }}