# ------------------------------
# グループを作成する
# ------------------------------

---
- hosts: all
  sudo: true
  user: ansible

  vars_files:
    - ./vars/groups.yml

  tasks:
    - name: addusers
      group:
       name: "{{ item.name }}"
       gid: "{{ item.gid }}"
#       state: absent      #削除時にコメントアウト解除する 
      with_items: 
        - "{{ groups }}"